### ISSUE TITLE
Player doesn't understand the bound of the field

### ISSUE THREAD

**Issue by Chanisco** [KevinBreurken/ProeveVanBekwaamheid#2]
On **Usertesting** the player stayed in within the first part of the sea.
Not knowing that the field was interactible.
We need to make the player understand sooner that you could drive around the sea freely

**Comment by KevinBreurken** [comment]
is it that they didn't understand the bounds or they didn't knew that they could move?

**Comment by Chanisco** [comment]
They didn't know they could move futher than the borders
We need to show at the beginning something visual that you're already in the middle of the sea
